# File: azure-pipelines.yml

jobs:
- job:
  pool:
    vmImage: 'macOS-10.13'
  variables:
    name: $(BuildDefinitionName)-$(Rev:.r)
    x: 10
    a: $[counter(variables['x'], 5)]
  steps:
    - bash: echo $(x) is incremented by 0 to get $(a)
    - bash: echo Build Definition Name - $(name)
    - bash: echo Build Number $(Build.BuildNumber)
