# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

parameters:
    stage: ''
jobs:
- job: ${{ parameters.stage }}
    steps:
    - script:  |
        rm $(base_location)/${{ parameters.stage }}/*
        cp $(Build.SourcesDirectory)/* $(base_location)/${{ parameters.stage }}
    displayName: 'Copy source code to ${{ parameters.stage }} destination'